### ISSUE TITLE
Number of Sats Not showing

### ISSUE THREAD

**Issue by Bob-VK6ZGN** [domschl/RaspberryNtpServer#5]
Hi  Tks for your project
I have one small problem using Adafruit module and Rpi3 64bib Rasberian OS All good
with one exception Not sure what I am doing wrong But for SATS I just get [ -- ] when I have + 20 connected
Running
"Debian GNU/Linux 11 (bullseye)"
6.1.21-v8+ aarch64
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110]

??

**Comment by Bob-VK6ZGN** [comment]
Forget all I said    It appears GPSD was not running !!

**Comment by domschl** [comment]
- This might happen, if you use a very old version of `gpsd-py3`. You need at least version `0.3.0` (which was [published in 2017](https://github.com/MartijnBraam/gpsd-py3/releases/tag/0.3.0). Easiest way to check the version is to simply re-install `gpsd-py3`.

- Then start `cgps` and make sure that it says `Status: 3D fix (xx secs)`. There might be a large number of satellites in the list. However look at the right table's right-most column titled `Seen(x)/Used(y)`. Under bad conditions (e.g. no clear line of sight to the sky), you might have `Seen(20)/Used(0)`, which means: while `gpsd` knows of 20 satellites, it can't use any of them because reception is too weak. Each satellite that has an `N` in the `Use` column cannot be used to establish the precise time. If that's happening to you, you need to check your antenna and the antenna position.
